name: yapit_mobile
description: YapIt - Cross-platform real-time messaging mobile app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^1.0.1
  http: ^1.1.0
  shared_preferences: ^2.1.1
  jwt_decoder: ^2.0.1
  google_fonts: ^4.0.0
  cached_network_image: ^3.2.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
